
indices of matched individuals 
```{r}
ind_MENSA <- c(1, 4, 13, 15, 16, 18, 20, 21, 23, 26)
ind_Kont <- c(10, 16, 23, 31, 35, 37, 38, 41, 42, 47, 48, 49, 50, 51, 52, 60,
              61, 65, 68, 81, 83, 91, 95, 96, 97)
```

```{r}
source('Transform_data.R')
```

```{r warning=F}
EyePos_exemple_M_v18 <- Transform_data(path = 'Hochbegabte-Critical-Stimuli-Export/Vid18_car_cornfield.csv')
str(EyePos_exemple_M_v18)
EyePos_exemple_M_v18_Matched <- EyePos_exemple_M_v18[, , ind_MENSA]
str(EyePos_exemple_M_v18_Matched)
```

```{r warning=F}
EyePos_exemple_K_v18 <- Transform_data(path = 'Kontrollgruppe-Critical-Stimuli-Export_190725_tw/Kontrollgruppe-N102_Raw-Data_Video-18_Car-Cornfield_excel.csv')
str(EyePos_exemple_K_v18)
EyePos_exemple_K_v18_Matched <- EyePos_exemple_K_v18[, , ind_Kont]
str(EyePos_exemple_K_v18_Matched)
```

## Gruppenvergleich für car cornfield:

Laden des Mehrgruppenmodells:
```{r}
source('Funktionen_Modelling_Mehrgruppenmodell.R')
```
Einlesen der AOIs:
```{r }
load('Visual_Features_vid18/car.corn_dynamic_AOI.Rdata') 
# List_AOI_car.cornfield_dyn
load('Visual_Features_vid18/car.corn_static_AOI.Rdata') 
# AOI_car.cornfield_stat
```
Ausführung des Gruppenmodells:
```{r }
Lasso_Group_vid18 <- 
  Final_Lasso(EyePos_exemple_MENSA = EyePos_exemple_M_v18_Matched, 
            EyePos_exemple_Kont = EyePos_exemple_K_v18_Matched,
            vidheight = 576, vidwidth = 720,
            vidheight_monitor = 1080, vidwidth_monitor = 1350, Nmap = 6, 
            nframes = 149, path_all = "./Visual_Features_vid18",
            listname_AOI_dyn = List_AOI_car.cornfield_dyn, 
            listname_AOI_stat = AOI_car.cornfield_stat, least_square = TRUE)
```
Graphische Veranschaulichung der Bestimmtheitsmaße $R^2$:
```{r }
plot(Lasso_Group_vid18$r2_adj)
```
Graphische Veranschaulichung der Vergleichsmetrik $D$:
```{r eval = F}
plot(Lasso_Group_vid18$vergleich)
min(Lasso_Group_vid18$vergleich)
max(Lasso_Group_vid18$vergleich)
```
Graphische Veranschaulichung der Feature-Map-Gewichtungen:
```{r }
beta <- Lasso_Group_vid18$beta


beta_norm <- matrix(nrow = nrow(beta), ncol = ncol(beta))
beta_norm[, 1] <- beta[, 1] 
beta_norm[, 2] <- beta[, 2]
beta_norm[, 3] <- beta[, 3]
beta_norm[, 4] <- beta[, 4]
beta_norm[, 5] <- beta[, 5]
beta_norm[, 6] <- beta[, 6]

beta_norm[, 7] <- beta[, 7] + beta[, 1]
beta_norm[, 8] <- beta[, 8] + beta[, 2]
beta_norm[, 9] <- beta[, 9] + beta[, 3]
beta_norm[, 10] <- beta[, 10] + beta[, 4]
beta_norm[, 11] <- beta[, 11] + beta[, 5]
beta_norm[, 12] <- beta[, 12] + beta[, 6]

require('plotly')

plot_ly(x = ~1:nrow(beta_norm), y = ~beta_norm[, 1], name = 'Static', 
        mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 1], name = 'Static Mensa', color = I("blue"),
            mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 2], name = 'Dynamic Mensa', color = I("orange"), 
            mode = 'lines'
            ) %>%
  add_trace(y = ~beta_norm[, 3], name = 'Center Bias Mensa', 
            color = I("darkgreen"),
            mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 4], name = 'Uniform Mensa', color = I("red"), 
            mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 5], name = 'AOI1 Mensa', color = I("purple"),
            mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 6], name = 'AOI2 Mensa', color = I("brown"), 
            mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 7], name = 'Static Kontrolle', opacity = .4,
            color = I("blue"), mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 8], name = 'Dynamic Kontrolle', opacity = .4,
            color = I("orange"), mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 9], name = 'Center Bias Kontrolle', opacity = .4,
            color = I("darkgreen"), mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 10], name = 'Uniform Kontrolle', opacity = .4,
            color = I("red"), mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 11], name = 'AOI1 Kontrolle', opacity = .4, 
            color = I("purple"), mode = 'lines') %>%
  add_trace(y = ~beta_norm[, 12], name = 'AOI2 Kontrolle', opacity = .4, 
            color = I("brown"), mode = 'lines') %>%
  layout(
   # title = "Regressionskoeffizienten (car.cornfield, Frame 2-169)",
      xaxis = list(title = "Framenummer"),
      yaxis = list(title = "Geschätzte FM-Gewichtungen")
    ) %>%
  layout(legend = list(orientation = 'h'))
```
